[package]
name = "grf_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
dialoguer = "0.11.0"
indicatif = { version = "0.17.8", features = ["rayon"] }
peroxide = { version = "0.37", features = ["plot", "parquet"] }
rayon = "1.9.0"
rugfield = "0.2.0"
